Logging into Discord...
Login successful. (2.8293ms)

-----------------
Red - Discord Bot
-----------------
DunkasBot#8349

Connected to:
3 servers
43 channels
151 users

Prefix: !
Owner: Dunkas#3452
12/16 active cogs with 94 commands
-----------------

Use this url to bring your bot to a server:
https://discordapp.com/oauth2/authorize?client_id=283680505545752577&scope=bot

Official server: https://discord.gg/red
Make sure to keep your bot updated. Select the 'Update' option from the launcher.
[03/03/2017 13:03] ERROR red on_command_error 363: Exception in command 'updateall'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/dunkas/BeepBoopBot/cogs/steam.py", line 127, in updateall
    is_admin = discord.utils.get(ctx.message.author.roles, name=admin_role) is not None
NameError: name 'admin_role' is not defined
[03/03/2017 13:11] ERROR red on_command_error 363: Exception in command 'updateall'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/dunkas/BeepBoopBot/cogs/steam.py", line 127, in updateall
    is_admin = discord.utils.get(ctx.message.author.roles, name=admin_role) is not None
NameError: name 'admin_role' is not defined
[03/03/2017 13:18] ERROR red on_command_error 363: Exception in command 'updateall'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/dunkas/BeepBoopBot/cogs/steam.py", line 111, in updateall
    is_admin = discord.utils.get(author.roles, name=self.admin_role) is not None
NameError: name 'author' is not defined
[03/03/2017 13:20] ERROR red on_command_error 363: Exception in command 'updateall'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/dunkas/BeepBoopBot/cogs/steam.py", line 111, in updateall
    author = ctx.message.author
NameError: name 'author' is not defined
[03/03/2017 13:20] ERROR red on_command_error 363: Exception in command 'updateall'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/dunkas/BeepBoopBot/cogs/steam.py", line 115, in updateall
    for discordID in steamList:
NameError: name 'steamList' is not defined
[03/03/2017 13:21] ERROR red on_command_error 363: Exception in command 'updateall'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/dunkas/BeepBoopBot/cogs/steam.py", line 116, in updateall
    updateBTS(self, discordID)
NameError: name 'updateBTS' is not defined
[03/03/2017 13:22] ERROR red on_command_error 363: Exception in command 'updateall'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/dunkas/BeepBoopBot/cogs/steam.py", line 116, in updateall
    self.updateBTS(self, discordID)
TypeError: updateBTS() takes 2 positional arguments but 3 were given
[03/03/2017 13:26] ERROR owner _reload 157: ('invalid syntax', ('/home/dunkas/BeepBoopBot/cogs/steam.py', 120, 8, '\t\t\t\ti++\n'))
Traceback (most recent call last):
  File "/home/dunkas/BeepBoopBot/cogs/owner.py", line 796, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/dunkas/BeepBoopBot/cogs/steam.py", line 120
    i++
      ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dunkas/BeepBoopBot/cogs/owner.py", line 151, in _reload
    self._load_cog(module)
  File "/home/dunkas/BeepBoopBot/cogs/owner.py", line 800, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('/home/dunkas/BeepBoopBot/cogs/steam.py', 120, 8, '\t\t\t\ti++\n'))
[03/03/2017 13:26] ERROR red <module> 620: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 662, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/aiohttp/client.py", line 202, in _request
    yield from resp.start(conn, read_until_eof)
  File "lib/aiohttp/client_reqrep.py", line 640, in start
    message = yield from httpstream.read()
  File "lib/aiohttp/streams.py", line 641, in read
    result = yield from super().read()
  File "lib/aiohttp/streams.py", line 476, in read
    yield from self._waiter
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
aiohttp.errors.ServerDisconnectedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "red.py", line 601, in <module>
    loop.run_until_complete(main(bot))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "red.py", line 590, in main
    yield from bot.connect()
  File "lib/discord/client.py", line 452, in connect
    self.ws = yield from DiscordWebSocket.from_client(self, resume=resume)
  File "lib/discord/gateway.py", line 193, in from_client
    gateway = yield from client.http.get_gateway()
  File "lib/discord/http.py", line 631, in get_gateway
    data = yield from self.request(Route('GET', '/gateway'))
  File "lib/discord/http.py", line 136, in request
    r = yield from self.session.request(method, url, **kwargs)
  File "lib/aiohttp/client.py", line 555, in __iter__
    resp = yield from self._coro
  File "lib/aiohttp/client.py", line 209, in _request
    raise aiohttp.ClientResponseError() from exc
aiohttp.errors.ClientResponseError
/home/dunkas/BeepBoopBot/cogs/steam.py:116: RuntimeWarning: coroutine 'steam.updateBTS' was never awaited
  self.updateBTS(self, discordID)
/home/dunkas/BeepBoopBot/cogs/steam.py:116: RuntimeWarning: coroutine 'steam.updateBTS' was never awaited
  self.updateBTS(self, discordID)
Traceback (most recent call last):
  File "/home/dunkas/BeepBoopBot/cogs/owner.py", line 796, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/dunkas/BeepBoopBot/cogs/steam.py", line 120
    i++
      ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dunkas/BeepBoopBot/cogs/owner.py", line 151, in _reload
    self._load_cog(module)
  File "/home/dunkas/BeepBoopBot/cogs/owner.py", line 800, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('/home/dunkas/BeepBoopBot/cogs/steam.py', 120, 8, '\t\t\t\ti++\n'))
Task was destroyed but it is pending!
task: <Task pending coro=<Streams.stream_checker() running at /home/dunkas/BeepBoopBot/cogs/streams.py:455> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.queue_scheduler() running at /home/dunkas/BeepBoopBot/cogs/audio.py:2080> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.disconnect_timer() running at /home/dunkas/BeepBoopBot/cogs/audio.py:1963> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.reload_monitor() running at /home/dunkas/BeepBoopBot/cogs/audio.py:2084> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.cache_manager() running at /home/dunkas/BeepBoopBot/cogs/audio.py:1915> wait_for=<Future pending cb=[Task._wakeup()]>>
CogLoadError: ('invalid syntax', ('/home/dunkas/BeepBoopBot/cogs/steam.py', 121, 63, '\t\tawait self.bot.say("Success: " + str(i) " profile(s) updated")\n'))
[03/03/2017 13:28] ERROR red load_cogs 560: ('invalid syntax', ('/home/dunkas/BeepBoopBot/cogs/steam.py', 121, 63, '\t\tawait self.bot.say("Success: " + str(i) " profile(s) updated")\n'))
Traceback (most recent call last):
  File "/home/dunkas/BeepBoopBot/cogs/owner.py", line 796, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/dunkas/BeepBoopBot/cogs/steam.py", line 121
    await self.bot.say("Success: " + str(i) " profile(s) updated")
                                                                ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "red.py", line 557, in load_cogs
    owner_cog._load_cog(extension)
  File "/home/dunkas/BeepBoopBot/cogs/owner.py", line 800, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('/home/dunkas/BeepBoopBot/cogs/steam.py', 121, 63, '\t\tawait self.bot.say("Success: " + str(i) " profile(s) updated")\n'))

Failed to load: cogs.steam

Logging into Discord...
Login successful. (2.716794ms)

-----------------
Red - Discord Bot
-----------------
DunkasBot#8349

Connected to:
3 servers
43 channels
151 users

Prefix: !
Owner: Dunkas#3452
12/16 active cogs with 94 commands
-----------------

Use this url to bring your bot to a server:
https://discordapp.com/oauth2/authorize?client_id=283680505545752577&scope=bot

Official server: https://discord.gg/red
Make sure to keep your bot updated. Select the 'Update' option from the launcher.
[03/03/2017 13:28] ERROR owner _reload 157: ('invalid syntax', ('/home/dunkas/BeepBoopBot/cogs/steam.py', 121, 63, '\t\tawait self.bot.say("Success: " + str(i) " profile(s) updated")\n'))
Traceback (most recent call last):
  File "/home/dunkas/BeepBoopBot/cogs/owner.py", line 796, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/dunkas/BeepBoopBot/cogs/steam.py", line 121
    await self.bot.say("Success: " + str(i) " profile(s) updated")
                                                                ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dunkas/BeepBoopBot/cogs/owner.py", line 151, in _reload
    self._load_cog(module)
  File "/home/dunkas/BeepBoopBot/cogs/owner.py", line 800, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('/home/dunkas/BeepBoopBot/cogs/steam.py', 121, 63, '\t\tawait self.bot.say("Success: " + str(i) " profile(s) updated")\n'))
Traceback (most recent call last):
  File "/home/dunkas/BeepBoopBot/cogs/owner.py", line 796, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/dunkas/BeepBoopBot/cogs/steam.py", line 121
    await self.bot.say("Success: " + str(i) " profile(s) updated")
                                                                ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dunkas/BeepBoopBot/cogs/owner.py", line 151, in _reload
    self._load_cog(module)
  File "/home/dunkas/BeepBoopBot/cogs/owner.py", line 800, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('/home/dunkas/BeepBoopBot/cogs/steam.py', 121, 63, '\t\tawait self.bot.say("Success: " + str(i) " profile(s) updated")\n'))
Task was destroyed but it is pending!
task: <Task pending coro=<Streams.stream_checker() running at /home/dunkas/BeepBoopBot/cogs/streams.py:455> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.queue_scheduler() running at /home/dunkas/BeepBoopBot/cogs/audio.py:2080> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.disconnect_timer() running at /home/dunkas/BeepBoopBot/cogs/audio.py:1963> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.cache_manager() done, defined at /home/dunkas/BeepBoopBot/cogs/audio.py:1908> wait_for=<Future pending cb=[Task._wakeup()]>>
Logging into Discord...
Login successful. (2.678789ms)

-----------------
Red - Discord Bot
-----------------
DunkasBot#8349

Connected to:
3 servers
43 channels
150 users

Prefix: !
Owner: Dunkas#3452
13/16 active cogs with 98 commands
-----------------

Use this url to bring your bot to a server:
https://discordapp.com/oauth2/authorize?client_id=283680505545752577&scope=bot

Official server: https://discord.gg/red
Make sure to keep your bot updated. Select the 'Update' option from the launcher.
[03/03/2017 16:50] ERROR red on_command_error 363: Exception in command 'wiff'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/dunkas/BeepBoopBot/cogs/xcog.py", line 31, in wiff
    wiffnum = int(self.countComs["wiff"])
KeyError: 'wiff'
[04/03/2017 01:11] WARNING audio _play 810: I can't play URL below because it is too long. Use [p]audioset maxlength to change this.

[SEARCH:]darude sandstorm flute 10 hour
[04/03/2017 01:14] WARNING audio _play 810: I can't play URL below because it is too long. Use [p]audioset maxlength to change this.

https://youtu.be/s_m-Ez3W5h4
